#!/usr/bin/python
#
# RADCORE - RADio COmmunication REcorder
# Copyright (C) 2014-2015 Anton Komarov
#
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program; 
# if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import os
import sys
import yaml
import time
import signal
import jinja2
import shutil
import random
import logging
import argparse
import requests
import threading
import subprocess

from scanner.uniden import *

audio_profiles={'high':{'rate':44100, 'format':'S16_LE', 'depth':2}, 
		'mod':{'rate':16000, 'format':'S16_LE', 'depth':2},
		'low':{'rate':8000, 'format':'S8', 'depth':1}}
dsnoop={}
icao_codes=[]
metars={}

all_processes=[]
sox_term_proc=[]
sox_threads=[]

def signal_handler(signal, frame):
	for a in all_processes:
		try:
			a.kill()
			logger.info('Killing process PID=%s' % a.pid)
		except Exception:
			logger.error('Cant kill process.')
			pass			
        sys.exit(0)

def record_uniden(au,sc,te,ic,station):

	try:	
		dt=te['dir']
		wt=te['wav']
		et=te['egc']
	except Exception:
		logger.error('Missing vars in templates!')
		return

	try:
		it=te['ice']
	except Exception:
		it=''
		pass

	try:
		card=dsnoop[au['card']]
		audio_format=au['format']
		rate=audio_profiles[au['profile']]['rate']
		fmt=audio_profiles[au['profile']]['format']
		bits=8*audio_profiles[au['profile']]['depth']
	except Exception:
		logger.error('Missing vars in audio!')
		return

	try:
		port=''.join(['/dev/scanners/',str(sc['port'])])
		s=UnidenScanner(port,str(sc['speed']))
	except Exception:
		logger.error('Cant create Uniden instance. Vars missing?')
		return

	try:
		s.set_volume(sc['volume'])
		s.set_squelch(sc['squelch'])
	except Exception:
		logger.error('Volume or squelch failed to set up!')
		pass

	collect_uids=False
	if 'collect_uids' in sc:
		if sc['collect_uids']=='on':
			logger.info('%s: collecting uids is on, setting up scanner.' % sc['name'])
			s.enter_program_mode()
			s.settings.get_data()
			s.settings.scanner_option['disp_uid']='1'
			s.settings.scanner_option['disp_mode']='MODE2'
			s.settings.set_data()
			s.exit_program_mode()
			s.push_key('press','scan')
			collect_uids=True
			uids=[]

	a=None

	sql=''
	psql=''
	ft=''
	pft=''

	while 1:
		psql=sql
		pft=ft

		try:
			cur=s.get_reception_status() # here we have timeout 10ms
		except Exception:
			logger.error('%s: got corrupted reception status.' % sc['name'])
			continue

		if type(cur) != type(dict()):
			logger.error('%s: returned status but it is not dictionary.' % sc['name'])
			continue

		sql=cur['sql']
		mute=cur['mute']
		ft=cur['frq_tgid']

		logger.debug('%s: SQL=%s, MUTE=%s, FT=%s', sc['name'], sql, mute, ft)

		# transition '' -> 1
		if sql=='1' and psql=='':
			
			yyyy=time.strftime('%Y')
			mm=time.strftime('%m')
			dd=time.strftime('%d')
			HH=time.strftime('%H')
			MM=time.strftime('%M')
			SS=time.strftime('%S')
			frq=cur['frq_tgid']
			tvars={'system':cur['name1'], 'group':cur['name2'], 'channel':cur['name3'],
					'year':yyyy, 'mon':mm, 'day':dd, 'hour':HH, 'min':MM, 'sec':SS,
					'frqtgid':cur['frq_tgid']}
			p=dt % tvars
			f=wt % tvars

			if cur['name2']=='' or cur['name3']=='':
				p=et % tvars

			try:
				os.makedirs(p)
			except OSError:
				pass

			fname=''.join([p,'/',f,'.',audio_format])

			cmd=['sox','-q','-e','signed','-b',str(bits),'-c1','-t','alsa',card,'-r',str(rate),fname]
			try:
				a = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
				all_processes.append(a)
				logger.info('%s: PID=%s recording to %s', sc['name'], a.pid, fname)
			except Exception, e:
				logger.error('%s: subproccess failed to start %s' % (sc['name'],str(e)))

			try:
				if ic['live']=='on':

					meta=it % tvars
					meta=meta.replace(' ', '+')
					meta_update(meta,ic,station)
			except Exception:
				pass

			continue

		# transition 1 -> '', 0 -> ''
		# to take into account time scanner waits before moving to next channel
		# or during sql=1 frequency is changed we need stop recording and set sql to ''
		if ((sql=='' and psql!=sql) or (sql==1 and pft!=ft)) and a:

			logger.info('%s: SIGTERM sent to PID=%s', sc['name'], a.pid)
			a.terminate()
			#a.send_signal(signal.SIGINT)
			#logger.info('%s: process with PID=%s returns %s', sc['name'], a.pid, a.returncode)
			#a.kill()
			#try:
			#	all_processes.pop(all_processes.index(a))
			#except Exception:
			#	pass
			sox_term_proc.append(a)

			a=None

			try:
				if ic['live']=='on':
					meta='SILENCE'
					meta_update(meta,ic,station)
			except Exception:
				pass
		
			if collect_uids:
				uids_fname=''.join([p,'/',f,'.txt'])
				uids_str='\n'.join(uids)
				logger.info('%s: saving uids to %s' % (sc['name'],uids_fname))
			        uids_file=open(uids_fname,'w')
				uids_file.write('%s' % uids_str)
			        uids_file.close()
				uids=[]

			sql=''

			continue

		if sql=='1' and collect_uids:
			try:
				cur_status=s.get_current_status()
				uids.append(cur_status['char'][2])
			except Exception:
				logger.error('%s: Cant append uid' % sc['name'])
				pass

def record_simple(au,sc,te,ic,station):

	try:	
		dt=te['dir']
		wt=te['wav']
	except Exception:
		logger.error('Missing vars in templates!')
		return

	try:
		card=dsnoop[au['card']]
		audio_format=au['format']
		rate=audio_profiles[au['profile']]['rate']
		fmt=audio_profiles[au['profile']]['format']
		bits=8*audio_profiles[au['profile']]['depth']
	except Exception:
		logger.error('Missing vars in audio!')
		return

	try:
		it=te['ice']
	except Exception:
		it=''
		pass

	tmpname=''.join(['/tmp/',card,'.',audio_format])

	while 1:

		cmd=['sox','-q','-e','signed','-b',str(bits),'-c1','-t','alsa',card,
			'-r',str(rate),tmpname,'silence','1','5','2%','1','0:00:01','2%']
		a = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
		all_processes.append(a)
		a.communicate()
		yyyy=time.strftime('%Y')
		mm=time.strftime('%m')
		dd=time.strftime('%d')
		HH=time.strftime('%H')
		MM=time.strftime('%M')
		SS=time.strftime('%S')
		tvars={'year':yyyy, 'mon':mm, 'day':dd, 'hour':HH, 'min':MM, 'sec':SS}

		try:
			all_processes.pop(all_processes.index(a))
		except Exception:
			pass

		try:
			p=dt % tvars
			f=wt % tvars
		except Exception:
			logger.error('Template definitions are broken!')
			return

		try:
			os.makedirs(p)
		except OSError:
			pass

		fname=''.join([p,'/',f,'.',audio_format])

		try:
			shutil.move(tmpname,fname)
		except Exception, e:
			logger.error('Cant rename file: %s.' % e)
			pass

		try:
			if ic['live']=='on': meta_update('',ic,station)
		except Exception:
			pass

def record_aor():pass
	#TODO AOR 8200 Mk3

def broadcast(au,ic):
		
	tvars={}
	templateLoader=jinja2.FileSystemLoader(searchpath='/')
	templateEnv=jinja2.Environment(loader=templateLoader)
	template=templateEnv.get_template('/opt/etc/darkice.conf.j2')
	tvars.update(au)
	tvars.update(ic)
	tvars['rate']=audio_profiles[au['profile']]['rate']
	tvars['depth']=8*int(audio_profiles[au['profile']]['depth'])
	tvars['card']=dsnoop[au['card']]
	config=template.render(tvars)
	cfname=''.join(['/tmp/',tvars['host'],tvars['mount'],'.conf'])
	try:
		cfile=open(cfname,'w')
		cfile.write('%s' % config)
		cfile.close()
	except Exception, e:
		logger.error('%s: config file write failed %s' % (tvars['mount'],str(e)))
		return
	cmd=['darkice','-c',cfname]
	try:
		a = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
	except Exception, e:
		logger.error('%s: darkice start failed %s' % (tvars['mount'],str(e)))
		a.kill()
		return
	logger.info('%s: darkice started with PID=%s' % (tvars['mount'],a.pid))
	all_processes.append(a)

def meta_update(meta,ic,station):

	metar=''
	try:
		metar=metars[station]
	except Exception:
		pass

	metaurl='http://'+ic['host']+':'+str(ic['port'])+'/admin/metadata?mount=/'+ic['mount']+'&mode=updinfo&song='
	req=metaurl+meta+' '+metar
	try:
		r=requests.get((req),auth=('source',ic['pass']),timeout=0.1)
		#if r.status_code != 200: logger.error('%s: cannot update meta.' % ic['mount'])
	except Exception, e:
		#logger.error('%s: requests error %s' % (ic['mount'],str(e)))
		pass

def get_metar(sc):

	while 1:
		url='http://weather.noaa.gov/pub/data/observations/metar/stations/'+str(sc)+'.TXT'
		r=requests.get(url)
		if r.status_code !=200: metars[sc]='NO METAR DATA'
		metar=r.text.split('\n')
		metars[sc]=metar[1]
		time.sleep(1800)

def asound_gen():

	i=0
	tvars=[]

	ans=subprocess.check_output(["cat "+"/proc/asound/card*/id"],shell=True)
	ans=ans.split('\n')

	for card in ans:
        	if card!='':
                	tvars.append({'index':i, 'card':card, 'rand':random.randrange(1024,1048576)})
	                dsnoop.update({card:'plug:dsnoop'+str(i)})
        	        i=i+1

	templateLoader=jinja2.FileSystemLoader(searchpath='/')
	templateEnv=jinja2.Environment(loader=templateLoader)
	template=templateEnv.get_template('/opt/etc/asound.conf.j2')
	config=template.render(items=tvars)

	cfname='/etc/asound.conf'
	cfile=open(cfname,'w')
	cfile.write('%s' % config)
	cfile.close()

def clean_term_sox():

	while 1:
		time.sleep(1)
		for a in sox_term_proc:
			a.poll()
			res=a.returncode
			logger.info('PID=%s exited with status %s.' % (a.pid,res))
			if res==None:
				time.sleep(2)
				a.poll()
				res=a.returncode
				if res==None:
					logger.info('PID=%s hangs?, try to kill it.' % a.pid)
					try:
						a.kill()
					except Exception, e:
						logger.error('Cannot kill PID=%s: %s' % (a.pid,str(e)))
						pass
					all_processes.pop(all_processes.index(a))
					sox_term_proc.pop(sox_term_proc.index(a))
				else:
					logger.info('PID=%s exited with status %s.' % (a.pid,res))
					all_processes.pop(all_processes.index(a))
					sox_term_proc.pop(sox_term_proc.index(a))
			else:
				all_processes.pop(all_processes.index(a))
				sox_term_proc.pop(sox_term_proc.index(a))
				
			
def monitor_sox_threads():

	while 1:
		for t in sox_threads:
			if not t.isAlive(): logger.error('thread is dead.')
			else: logger.info('thread is ok.')
		time.sleep(60)
		


class Whitelist(logging.Filter):
    def __init__(self, *whitelist):
        self.whitelist = [logging.Filter(name) for name in whitelist]

    def filter(self, record):
        return any(f.filter(record) for f in self.whitelist)

parser = argparse.ArgumentParser()
parser.add_argument('--config', type=str, default='/opt/etc/radcore.yml')
parser.add_argument('--log-file', type=str, default='/opt/var/log/radcore.log')
args=parser.parse_args()

logger = logging.getLogger()
logger.setLevel(logging.INFO)
fh = logging.FileHandler(args.log_file)
fh.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
logger.addHandler(fh)

for handler in logging.root.handlers:
        handler.addFilter(Whitelist('root','scanner'))

logger.info('Loading config file %s' % args.config)

try:
	instances=yaml.load(file(args.config,'r'))
except Exception:
	logger.critical('No config file found!')
	sys.exit(0)

asound_gen()

for ins in instances:

	icao_code='NONE'
	
	try:
		au=ins['audio']
		sc=ins['scanner']
		te=ins['templates']
	except Exception:
		logger.error('Missing mandatory config lines!')
		continue

	try:
		sc_name=sc['name']
	except Exception:
		logger.error('Scanner name MUST be assigned!')
		continue

	if 'icecast' in ins: ic=ins['icecast']
	else: ic={}

	if 'icao_code' in ins:
		icao_code=ins['icao_code']
		icao_codes.append(icao_code)

	if 'time_zone' in ins:
		os.environ['TZ']=ins['time_zone']
		time.tzset()

	rfunc=''.join(['record_',sc['type']])
	rt = threading.Thread(target=eval(rfunc), args = (au,sc,te,ic,icao_code))
	rt.daemon=True
	try:
		rt.start()
		logger.info('%s: recording thread started.' % sc_name)
		sox_threads.append(rt)
	except Exception, e:
		logger.error('%s: recording thread failed to start %s' % (sc_name,str(e)))
		pass

	if 'live' in ic:
		if ic['live']=='on':
			lt = threading.Thread(target=broadcast, args = (au,ic))
			lt.daemon=True
			try:
				lt.start()
				logger.info('%s: broadcast thread started.' % sc_name)
			except Exception, e:
				logger.error('%s: broadcast thread failed to start %s' % (sc_name,str(e)))
				pass
				
			

icao_codes=list(set(icao_codes))
for icao_code in icao_codes:
	mt = threading.Thread(target=get_metar, args=(icao_code,))
	mt.daemon=True
	mt.start()
	logger.info('%s: fetching METAR for %s started.' % (sc_name,icao_code))

stpt = threading.Thread(target=clean_term_sox)
stpt.daemon=True
stpt.start()
logger.info('sox terminated process cleaner started.')

mst = threading.Thread(target=monitor_sox_threads)
mst.daemon=True
mst.start()
logger.info('sox threads monitor started.')

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)
signal.pause()
